stages:
  - deploy

variables:
  DEPLOY_PATH: "/var/www/ollama-api"       # Путь для деплоя на сервере
  SERVER_IP: "188.243.28.22"               # IP вашего сервера
  SERVER_USERNAME: "bogd"                  # SSH-юзер для подключения
  PM2_PROCESS_NAME: "ollama-api"           # Имя процесса в PM2

before_script:
  - 'which ssh-agent || apt-get update -qy && apt-get install -y openssh-client'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy:
  stage: deploy
  image: node:20
  script:
    - ssh $SERVER_USERNAME@$SERVER_IP "mkdir -p $DEPLOY_PATH"  # Убедитесь, что директория существует
    - rsync -avz --delete . $SERVER_USERNAME@$SERVER_IP:$DEPLOY_PATH  # Копируем все файлы (не только dist)
    - ssh $SERVER_USERNAME@$SERVER_IP "cd $DEPLOY_PATH && npm install --production"  # Устанавливаем зависимости
    - ssh $SERVER_USERNAME@$SERVER_IP "cd $DEPLOY_PATH && npm run build"  # Собираем приложение (если у вас есть команда build)
    - ssh $SERVER_USERNAME@$SERVER_IP "cd $DEPLOY_PATH && pm2 start ecosystem.config.cjs --name $PM2_PROCESS_NAME"  # Запуск через PM2
  only:
    - main  # Выполняем деплой только с основной ветки
