stages:
  - build
  - deploy

before_script:
  - 'which ssh-agent || apt-get update -qy && apt-get install -y openssh-client'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - apt-get update -qy && apt-get install -y rsync

build:
  stage: build
  image: node:20
  script:
    - npm ci 
    - npm run build 

  artifacts:
    paths:
      - dist
      - ecosystem.config.cjs
    expire_in: 1 hour

deploy:
  stage: deploy
  image: node:20
  script:
    - ssh $SERVER_USERNAME@$SERVER_IP "mkdir -p $DEPLOY_PATH"
    
    - rsync -avz --delete dist/ $SERVER_USERNAME@$SERVER_IP:$DEPLOY_PATH
    - rsync -avz --delete ecosystem.config.cjs $SERVER_USERNAME@$SERVER_IP:$DEPLOY_PATH
    
    - ssh $SERVER_USERNAME@$SERVER_IP "cd $DEPLOY_PATH && pm2 start ecosystem.config.cjs --name $PM2_PROCESS_NAME"

  only:
    - main
  dependencies:
    - build
